### PR TITLE
Add support for running as `python -m detox ...`

### PR DESCRIPTION
**Pull request by AndreLouisCaron**
Fixes tox-dev/tox#468.

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
oh, and please a changelog entry

**Comment by AndreLouisCaron** [comment]
I'll gladly add it, but I don't see any tags for anything above 0.9, so I'm not sure under which version this should go.  Should it be under 0.11 or 0.12?

**Comment by obestwalter** [comment]
Released version is 0.10 (https://pypi.python.org/pypi/detox) so 0.11 is the next version.

**Comment by obestwalter** [comment]
Changelog already updated. Thanks @AndreLouisCaron!

**Comment by AndreLouisCaron** [comment]
Thanks for merging this!

No pressure, but do you have an ETA on the 0.11 release?

**Comment by obestwalter** [comment]
Good question. I guess I could make a release for tox and detox this friday before to many changes accumulate. If there are no objections. @hpk42?

**Pull request merged**
